name: tdoa  # environment name
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy == 5.3
  - jupyter
  - matplotlib
  - numpy == 1.24.3
  - pip
  - python == 3.11.0
  - scipy == 1.10.1
  - pip:
    - ipykernel
    - astrospice == 0.2.0
    - pyspedas
    - pytplot-mpl-temp
